class EntranceName():
    Menu_StartGame = "Menu - Start Game"
    Haven_WindingGlade = "Haven Teleport Stone - Winding Glade"
    Haven_WestHaven_DetonateWall = "Haven - West Haven Detonate Wall"
    Haven_MystralWoods = "Haven - Mystral Woods"
    MystralWoods_GreyleafHamlet = "Mystral Woods - Greyleaf_Hamlet"
    MystralWoods_PostCart = "Mystral Woods - Post Cart"
    MystralWoodsPostCart_GoblinCamp = "Mystral Woods Post Cart - Goblin Camp"
    MystralWoodsGoblinCamp_Lardee = "Mystral Woods Goblin Camp - Lardee"
    MystralWoodsLardee_DeepWoods = "Mystral Woods Lardee - Deep Woods"
    MystralWoodsLardee_OldMines = "Mystral Woods Lardee - Old Mines"
    MystralWoodsDeepWoods_Twiggs = "Mystral Woods Deep Woods - Twiggs"
    MystralWoodsDeepWoods_BackWoods = "Mystral Woods Deep Woods - Back Woods"
    MystralWoodsBackWoods_GreyleafNorth = "Mystral Woods Back Woods - Greyleaf Hamlet North"