class ItemName():
    ManaCharm = "Mana Charm"
    ManaLilyBulb = "Mana Lily Bulb"

    HealthUpgrade = "Health Upgrade"
    ManaUpgrade = "Mana Upgrade"
    WoodWretchElixer = "Wood Wretch Elixer"
    IceLizardElixer = "Ice Lizard Elixer"
    GhostQueenElixer = "Ghost Queen Elixer"

    FiveGreenBeads = "5 Green Soulbeads"
    TenGreenBeads = "10 Green Soulbeads"
    FifteenGreenBeads = "15 Green Soulbeads"
    TwentyFiveGreenBeads = "25 Green Soulbeads"
    ThirtyGreenBeads = "30 Green Soulbeads"
    FiftyGreenBeads = "50 Green Soulbeads"
    SeventyFiveGreenBeads = "75 Green Soulbeads"
    Purple_Soulbead = "Purple Soulbead"

    Spellbook = "Spellbook"
    ArchmagesRobe = "Archmages Robe"
    ApprenticeWand = "Apprentice Wand"
    IgniWand = "Igni Wand"
    AuraWand = "Aura Wand"
    GaeaWand = "Gaea Wand"
    AquaWand = "Aqua Wand"
    TrialWand = "Trial Wand"
    LifeStaff = "Life Staff"

    Immedi = "Immedi" #default Wind Element
    Actus = "Actus" #Default Fire Element
    Creo = "Creo" #Default Ice Element
    Ego = "Ego" #Default Earth Element

    TeleportRune = "Teleport Rune"
    DetonateRune = "Detonate Rune"
    RandomRune = "Random Rune"
    MoveRune = "Move Rune"
    HomingRune = "Homing Rune"
    RightRune = "Right Rune"
    MasteryRune = "Mastery Rune"
    ImpactRune = "Impact Rune"
    OverchargeRune = "Overcharge Rune"
    ProximityRune = "Proximity Rune"
    TimeRune = "Time Rune"
    BounceRune = "Bounce Rune"
    DuplicateRune = "Duplicate Rune"
    InverseRune = "Inverse Rune"
    EtherRune = "Ether Rune"
    SizeRune = "Size Rune"
    RainRune = "Rain Rune"

    BagOfWares = "Bag Of Wares"
    Token = "Token"
    BigKey = "Big Key"
    SkyShard = "Sky Shard"
    PortalStone = "PortalStone"
    BrokenPortalStone = "Broken PortalStone"
    Pitchfork = "Pitchfork"
    BoarMeat = "Boar Meat"
    HotBread = "Hot Bread"
    Flowers = "Flowers"
    Badge = "Badge"
    BottleForSpirits = "Bottle For Spirits"

    FixedMariesCart = "Fixed Maries Cart"
    MystralWoodsCleansed = "Mystral Woods Cleansed"
    DefeatSleet = "Defeat Ancient Lizard Sleet"
    DefeatGhostQueen = "Defeat Ghost Queen"
    EclipseApproaching = "Greyleaf Hamlet Eclipse Appraching"
    SkyTempleTorch = "Sky Temple Torch"
    Victory = "Victory"