class LocationName():
    Haven_InfrontOfTower = "Infront the Mages Tower"
    Haven_EnchanterManaLily = "Enchanters Mana Lily"
    Haven_ManaLilyTwo = "Mana Lily Two"
    Haven_ManaLilyThree = "Mana Lily Three"
    Haven_ManaLilyFour = "Mana Lily Four"
    Haven_ManaLilyFive = "Mana Lily Five"
    Haven_UpgradeFountainOne = "Upgrade Fountain One"
    Haven_UpgradeFountainTwo = "Upgrade Fountain Two"
    Haven_UpgradeFountainThree = "Upgrade Fountain Three"
    Haven_UpgradeFountainFour = "Upgrade Fountain Four"
    Haven_UpgradeFountainFive = "Upgrade Fountain Five"
    Haven_UpgradeFountainSix = "Upgrade Fountain Six"
    Haven_UpgradeFountainSeven = "Upgrade Fountain Seven"
    Haven_UpgradeFountainEight = "Upgrade Fountain Eight"
    Haven_UpgradeFountainNine = "Upgrade Fountain Nine"
    Haven_UpgradeFountainTen = "Upgrade Fountain Ten"
    Haven_UnderBridge = "Hiding under the bridge in Haven"
    Haven_RandomRunePuzzleRoom = "Haven - Random Rune Puzzle Room"

    WindingGlade_TeleportRunePuzzleRoom = "The Winding Glade - Teleport Rune Puzzle Room"

    MystralWoods_ManaLilyCelestialPuzzle = "Mystral Woods - Celastial Puzzle near Mana Lily"
    MystralWoods_ManaLily = "Mystral Woods - Mana Lily"
    MystralWoods_PostCart_PurpleBeadPuzzleRoom = "Mystral Woods Behind Cart - Purple Bead Puzzle Room"
    MystralWoods_GoblinCamp_BagOfWares = "Mystral Woods Goblin Camp - Bag Of Wares"
    MystralWoods_Lardee_MoveRune = "Mystral Woods Lardee Reward - Move Rune"
    MystralWoods_DeepWoods_BagOfWaresOne = "Mystral Woods Deep Woods - Bag Of Wares One"
    MystralWoods_DeepWoods_StrangeOldGoblin = "Mystral Woods Deep Woods - Strange Old Goblin"
    MystralWoods_DeepWoods_BagOfWaresTwo = "Mystral Woods Deep Woods - Bag Of Wares Two"
    MystralWoods_Twiggs_LifeElixer = "Mystral Woods Twiggs - Life Elixer"
 
    GreyleafHamlet_ManaLily = "Greyleaf Hamlet - Mana Lily"

    OldMinesLardee_BagOfWares = "Old Mines Lardee - Bag Of Wares"

    MystalWoodsMariesCart = "Mystral Woods - Maries Cart"
    Victory = "Victory"


    Placeholder_PurpleBead1 = "Placeholder_Purplebead1"
    Placeholder_PurpleBead2 = "Placeholder_PurpleBead2"
    Placeholder_PurpleBead3 = "Placeholder_PurpleBead3"
    Placeholder_PurpleBead4 = "Placeholder_PurpleBead4"
    Placeholder_PurpleBead5 = "Placeholder_PurpleBead5"
    Placeholder_PurpleBead6 = "Placeholder_PurpleBead6"
    Placeholder_PurpleBead7 = "Placeholder_PurpleBead7"
    Placeholder_PurpleBead8 = "Placeholder_PurpleBead8"
    Placeholder_PurpleBead9 = "Placeholder_PurpleBead9"
    Placeholder_PurpleBead10 = "Placeholder_PurpleBead10"
    Placeholder_PurpleBead11 = "Placeholder_PurpleBead11"
    Placeholder_PurpleBead12 = "Placeholder_PurpleBead12"
    Placeholder_PurpleBead13 = "Placeholder_PurpleBead13"
    Placeholder_PurpleBead14 = "Placeholder_PurpleBead14"
    Placeholder_PurpleBead15 = "Placeholder_PurpleBead15"
    Placeholder_PurpleBead16 = "Placeholder_PurpleBead16"
    Placeholder_PurpleBead17 = "Placeholder_PurpleBead17"
    Placeholder_PurpleBead18 = "Placeholder_PurpleBead18"
    Placeholder_PurpleBead19 = "Placeholder_PurpleBead19"
    Placeholder_PurpleBead20 = "Placeholder_PurpleBead20"
    Placeholder_PurpleBead21 = "Placeholder_PurpleBead21"
    Placeholder_PurpleBead22 = "Placeholder_PurpleBead22"
    Placeholder_PurpleBead23 = "Placeholder_PurpleBead23"
    Placeholder_PurpleBead24 = "Placeholder_PurpleBead24"
    Placeholder_PurpleBead25 = "Placeholder_PurpleBead25"
    Placeholder_PurpleBead26 = "Placeholder_PurpleBead26"
    Placeholder_PurpleBead27 = "Placeholder_PurpleBead27"

    Placeholder_ManaLily1 = "Placeholder_ManaLily1"
    Placeholder_ManaLily2 = "Placeholder_ManaLily2"
    Placeholder_DetonateRune = "Placeholder_DetonateRune"