class LocationName():
    Haven_InfrontOfTower = "Infront the Mages Tower"
    Haven_EnchanterManaLily = "Enchanters Mana Lily"
    Haven_ManaLilyTwo = "Mana Lily Two"
    Haven_ManaLilyThree = "Mana Lily Three"
    Haven_ManaLilyFour = "Mana Lily Four"
    Haven_ManaLilyFive = "Mana Lily Five"
    Haven_HealthFountainOne = "Health Fountain One"
    Haven_HealthFountainTwo = "Health Fountain Two"
    Haven_HealthFountainThree = "Health Fountain Three"
    Haven_HealthFountainFour = "Health Fountain Four"
    Haven_HealthFountainFive = "Health Fountain Five"
    Haven_ManaFountainOne = "Mana Fountain One"
    Haven_ManaFountainTwo = "Mana Fountain Two"
    Haven_ManaFountainThree = "Mana Fountain Three"
    Haven_ManaFountainFour = "Mana Fountain Four"
    Haven_ManaFountainFive = "Mana Fountain Five"
    Haven_UnderBridge = "Hiding under the bridge in Haven"
    Haven_RandomRunePuzzleRoom = "Haven - Random Rune Puzzle Room"

    WindingGlade_TeleportRunePuzzleRoom = "The Winding Glade - Teleport Rune Puzzle Room"

    MystralWoods_ManaLilyCelestialPuzzle = "Mystral Woods - Celastial Puzzle near Mana Lily"
    MystralWoods_ManaLily = "Mystral Woods - Mana Lily"

    GreyleafHamlet_ManaLily = "Greyleaf Hamlet - Mana Lily"

    Victory = "Victory"


    Placeholder_PurpleBead1 = "Placeholder_Purplebead1"
    Placeholder_PurpleBead2 = "Placeholder_PurpleBead2"
    Placeholder_PurpleBead3 = "Placeholder_PurpleBead3"
    Placeholder_PurpleBead4 = "Placeholder_PurpleBead4"
    Placeholder_PurpleBead5 = "Placeholder_PurpleBead5"
    Placeholder_PurpleBead6 = "Placeholder_PurpleBead6"
    Placeholder_PurpleBead7 = "Placeholder_PurpleBead7"
    Placeholder_PurpleBead8 = "Placeholder_PurpleBead8"
    Placeholder_PurpleBead9 = "Placeholder_PurpleBead9"
    Placeholder_PurpleBead10 = "Placeholder_PurpleBead10"
    Placeholder_PurpleBead11 = "Placeholder_PurpleBead11"
    Placeholder_PurpleBead12 = "Placeholder_PurpleBead12"
    Placeholder_PurpleBead13 = "Placeholder_PurpleBead13"
    Placeholder_PurpleBead14 = "Placeholder_PurpleBead14"
    Placeholder_PurpleBead15 = "Placeholder_PurpleBead15"
    Placeholder_PurpleBead16 = "Placeholder_PurpleBead16"
    Placeholder_PurpleBead17 = "Placeholder_PurpleBead17"
    Placeholder_PurpleBead18 = "Placeholder_PurpleBead18"
    Placeholder_PurpleBead19 = "Placeholder_PurpleBead19"
    Placeholder_PurpleBead20 = "Placeholder_PurpleBead20"
    Placeholder_PurpleBead21 = "Placeholder_PurpleBead21"
    Placeholder_PurpleBead22 = "Placeholder_PurpleBead22"
    Placeholder_PurpleBead23 = "Placeholder_PurpleBead23"
    Placeholder_PurpleBead24 = "Placeholder_PurpleBead24"
    Placeholder_PurpleBead25 = "Placeholder_PurpleBead25"
    Placeholder_PurpleBead26 = "Placeholder_PurpleBead26"
    Placeholder_PurpleBead27 = "Placeholder_PurpleBead27"
    Placeholder_PurpleBead28 = "Placeholder_PurpleBead28"
    Placeholder_ManaLily1 = "Placeholder_ManaLily1"
    Placeholder_ManaLily2 = "Placeholder_ManaLily2"
    Placeholder_DetonateRune = "Placeholder_DetonateRune"