class RegionName():
    Menu = "Menu"
    WindingGlade = "The Winding Glade"
    Haven = "Haven"
    WesternHaven = "Western Haven"
    MystralWoods = "Mystral Woods"
    MystralWoodsPostCart = "Mystral Woods - Post Cart Fixed"
    MystralWoodsGoblinCamp = "Mystral Woods - Goblin Camp"
    MystralWoodsLardeeArea = "Mystral Woods - Lardee Area"
    MystralWoodsDeepWoods = "Mystral Woods - Deep Woods"
    MystralWoodsTwiggs = "Mystral Woods - Twiggs"
    MystralWoodsBackWoods = "Mystral Woods - Back Woods"
    MystralWoodsBackWoodsWest = "Mystral Woods - Back Woods - West"
    MystralWoodsMiningArea = "Mystral Woods - Mining Area"
    OldMinesLardeeArea = "Old Mines - Lardee Area"
    Greyleaf_Hamlet_South = "Greyleaf Hamlet - South"
    Greyleaf_Hamlet_North = "Greyleaf Hamlet - North"
    Greyleaf_Hamlet = "Greyleaf Hamlet"

    RiseSouth = "The Rise - South"
    TheRise = "The Rise"
    RiseNorth = "The Rise - North"
    SkyTempleFrontDoor = "Sky Temple - Front Door Area"
    SkyTempleHub = "Sky Temple - Hub Area"
    SkyTempleHubNorth = "Sky Temple Hub - North Area"
    SkyTempleUpper = "Sky Temple Upper Area"
    LavaGrotto = "Lava Grotto"
    Highlands = "The Highlands"