class RegionName():
    Menu = "Menu"
    WindingGlade = "The Winding Glade"
    Haven = "Haven"
    WesternHaven = "Western Haven"
    MystralWoods = "Mystral Woods"
    MystralWoodsPostCart = "Mystral Woods - Post Cart Fixed"
    MystralWoodsGoblinCamp = "Mystral Woods - Goblin Camp"
    MystralWoodsLardeeArea = "Mystral Woods - Lardee Area"
    MystralWoodsDeepWoods = "Mystral Woods - Deep Woods"
    MystralWoodsTwiggs = "Mystral Woods - Twiggs"
    MystralWoodsBackWoods = "Mystral Woods - Back Woods"
    OldMinesLardeeArea = "Old Mines - Lardee Area"
    Greyleaf_Hamlet = "Greyleaf Hamlet"
    Greyleaf_Hamlet_North = "Greyleaf Hamlet - North"